services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env.local
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'True'
      PGADMIN_CONFIG_MASTER_PASSWORD: '${PGADMIN_CONFIG_MASTER_PASSWORD}'
    ports:
      - "${FORWARD_PGADMIN_PORT:-5050}:80"
    depends_on:
      - pgsql
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - app_net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "${FORWARD_REDISINSIGHT_PORT:-5540}:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight-data:/data
    networks:
      - app_net

volumes:
  pgadmin-data:
    driver: local
  redisinsight-data:
    driver: local
